apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert
  namespace: cert-manager
spec:
  secretName: example-cert-secret
  duration: 2160h
  renewBefore: 720h
  commonName: example.com
  dnsNames:
  - example.com
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
