apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentsurvey-deployment
  labels:
    app: studentsurvey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: studentsurvey
  template:
    metadata:
      labels:
        app: studentsurvey
    spec:
      containers:
      - name: studentsurvey
        image: vedanshadepu99/studentsurvey:IMAGE_TAG
        ports:
        - containerPort: 80
